Update test_run.yml

diff --git a/.github/workflows/test_run.yml b/.github/workflows/test_run.yml
--- a/.github/workflows/test_run.yml
+++ b/.github/workflows/test_run.yml
@@ -17,13 +17,16 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: "3.10"
-      - run: > 
+      - run: |
+          echo "Fetching artifact ID"
           ARTIFACT_ID=$(curl -L -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/Dan1lV1t/allure_integration/actions/artifacts?name=allure-results \
           | python3 -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id'])") \
-          && 
+          && echo "Artifact ID: $ARTIFACT_ID"
+      - run: |
+          echo "Downloading artifact"
           curl -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
@@ -37,7 +40,6 @@ jobs:
           name: allure-result
           path: allure-result
           retention-days: 1
-
 
   test:
     runs-on: ubuntu-latest
@@ -57,7 +59,7 @@ jobs:
           name: allure-result
           path: allure-result
       - name: Run test
-        run: pytest --alluredir=allure-result
+        run: pytest --alluredir=allure-result || echo "Tests failed"
       - name: Store allure results
         uses: actions/upload-artifact@v3
         with:
@@ -105,6 +107,7 @@ jobs:
       - name: Deploy to Github Pages
         id: deployment
         uses: actions/deploy-pages@v1.2.9
+
 
 
 
